# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new Quiz', max_length=200)),
                ('contentName', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
