# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20170208_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_Correct',
        ),
    ]
