# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='questions.Question')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='questions.Survey')),
            ],
            options={
                'db_table': 'graphic',
                'verbose_name_plural': 'Graphic',
            },
        ),
    ]
