# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20170228_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
